import "./globals.css";



export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="bg-gradient-to-br from-blue-50 via-purple-50/30 to-indigo-100/40">
    
        <main className="min-h-screen">
                    {children}
        </main>
      </body>
    </html>
  );
}
